[tool.poetry]
name = "diamond-miner-core"
version = "0.1.0"
description = ""
authors = ["Matthieu Gouel <matthieu.gouel@protonamil.com>"]

[tool.poetry.dependencies]
python = "^3.6"
clickhouse-driver = "^0.1.5"
cperm = "^0.1.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
