[tool.poetry]
name = "diamond-miner"
version = "0.1.0"
description = ""
authors = [
    "Kevin Vermeulen <kevin.vermeulen@columbia.edu>",
    "Matthieu Gouel <matthieu.gouel@lip6.fr>",
    "Maxime Mouchet <maxime.mouchet@lip6.fr>"
]
build = "build.py"

[tool.poetry.dependencies]
python = "^3.8"
aioch = "^0.0.2"
pygfc = "^0.2.0"

[tool.poetry.dev-dependencies]
black = { version = "^20.8b1", allow-prereleases = true }
Cython = "^0.29.22"
flake8 = "^3.8.4"
mypy = "^0.812"
pylint = "^2.7.2"
pytest = "^6.2"
pytest-asyncio = "^0.14.0"
pytest-cov = "^2.11.1"

[tool.pytest.ini_options]
addopts = "--cov=diamond_miner --cov-report term --doctest-ignore-import-errors --doctest-modules -o log_cli=true --log-cli-level info"

[build-system]
requires = ["poetry>=0.12", "setuptools>=40.6.0", "Cython>=0.29.0"]
build-backend = "poetry.masonry.api"
