[tool.poetry]
name = "diamond-miner-core"
version = "0.1.0"
description = ""
authors = ["Matthieu Gouel <matthieu.gouel@protonamil.com>"]

[tool.poetry.dependencies]
python = "^3.8"
clickhouse-driver = "^0.1.5"
cperm = "^0.1.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-asyncio = "^0.14.0"
flake8 = "^3.8.4"
black = {version = "^20.8b1", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
