name: Tests

on:
  push:
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: yandex/clickhouse-server
        ports: ['8123:8123']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: dioptra-io/setup-poetry-action@v1
      - name: Install package
        run: poetry install
      - name: Insert test data
        run: poetry run tests/data/insert.py
      - name: Run tests
        run: poetry run pytest --cov=diamond_miner --cov-report=xml
      - uses: codecov/codecov-action@v2
