name: Tests

on:
  push:
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: dioptra-io/setup-clickhouse-action@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Tests
        run: |
          poetry run tests/data/insert.py
          poetry run pytest -s --cov-report xml
      - uses: codecov/codecov-action@v2
